#!/usr/bin/env python3

import telnetlib
import json

HOST = "socket.cryptohack.org"
PORT = 11112

tn = telnetlib.Telnet(HOST, PORT)

def readline():
    return tn.read_until(b"\n")

def json_recv():
    line = readline()
    return json.loads(line.decode())

def json_send(hsh):
    request = json.dumps(hsh).encode()
    tn.write(request)

print(readline())
print(readline())
print(readline())
print(readline())

request = {
    "buy": "flag"
}

json_send(request)
response = json_recv()
print(response)


#Copy
#Run the script to get the flag
#$ python3 telnetlib_example_dbc6ff5dc4dcfac568d7978a801d3ead.py
# b"Welcome to netcat's flag shop!\n"
# b'What would you like to buy?\n'
# b"I only speak JSON, I hope that's ok.\n"
# b'\n'
# {'flag': 'crypto{sh0pp1ng_f0r_fl4g5}'}

#Copy
#crypto{sh0pp1ng_f0r_fl4g5}
